/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package soldproduct;

import dsupershop.Home;

/**
 *
 * @author user
 */
public class SoldProductInsert extends javax.swing.JFrame {

    /**
     * Creates new form SoldProductInsert
     */
    public SoldProductInsert() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        proId = new javax.swing.JTextField();
        proName = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        quan = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        insertButton = new javax.swing.JButton();
        insertButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 0));
        setMinimumSize(new java.awt.Dimension(800, 700));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("PRO_ID");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 30, 98, 35);

        jLabel2.setText("PRODUCT_NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 100, 86, 27);

        jLabel3.setText("Cust_ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 160, 98, 27);

        jLabel4.setText("Quantity");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 220, 98, 32);

        jLabel5.setText("Price");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(90, 300, 98, 31);

        proId.setBackground(new java.awt.Color(204, 204, 204));
        proId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proIdActionPerformed(evt);
            }
        });
        getContentPane().add(proId);
        proId.setBounds(220, 30, 280, 30);

        proName.setBackground(new java.awt.Color(204, 204, 204));
        proName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proNameActionPerformed(evt);
            }
        });
        getContentPane().add(proName);
        proName.setBounds(220, 100, 280, 30);

        custId.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(custId);
        custId.setBounds(220, 160, 280, 30);

        quan.setBackground(new java.awt.Color(204, 204, 204));
        quan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanActionPerformed(evt);
            }
        });
        getContentPane().add(quan);
        quan.setBounds(220, 230, 280, 30);

        price.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(price);
        price.setBounds(220, 300, 280, 30);

        insertButton.setText("Insert");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        getContentPane().add(insertButton);
        insertButton.setBounds(310, 350, 110, 50);

        insertButton1.setText("HOME");
        insertButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(insertButton1);
        insertButton1.setBounds(130, 350, 110, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
//      int status;
        SoldProductClient cli = new SoldProductClient();
        int proID;
        proID = Integer.parseInt(proId.getText());
        String pronm = proName.getText();
        int custID;
        custID = Integer.parseInt(custId.getText());
        int qua = Integer.parseInt(quan.getText());

        int pr;
        pr = Integer.parseInt(price.getText());
        System.out.println(proID + "" + pronm + "" + custID + "" + qua + "" + pr);
        int st = cli.sendData(proID, pronm, custID, qua, pr);

        if (st == 1)
        dispose();

    }//GEN-LAST:event_insertButtonActionPerformed

    private void proIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proIdActionPerformed

    private void proNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proNameActionPerformed

    private void quanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quanActionPerformed

    private void insertButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButton1ActionPerformed
        // TODO add your handling code here:
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_insertButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SoldProductInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SoldProductInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SoldProductInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SoldProductInsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SoldProductInsert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custId;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton insertButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField price;
    private javax.swing.JTextField proId;
    private javax.swing.JTextField proName;
    private javax.swing.JTextField quan;
    // End of variables declaration//GEN-END:variables
}
