/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsupershop;

import addProduct.AddProducts;
import customer.Customer;
import soldproduct.*;
import record.*;

/**
 *
 * @author success
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBproducts = new javax.swing.JButton();
        jBsell = new javax.swing.JButton();
        jBrecord = new javax.swing.JButton();
        jBstock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jBproducts.setBackground(new java.awt.Color(255, 51, 0));
        jBproducts.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBproducts.setText("Add Product");
        jBproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBproductsActionPerformed(evt);
            }
        });

        jBsell.setBackground(new java.awt.Color(255, 51, 0));
        jBsell.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBsell.setText("Sale Product");
        jBsell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsellActionPerformed(evt);
            }
        });

        jBrecord.setBackground(new java.awt.Color(255, 51, 0));
        jBrecord.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBrecord.setText("Record");
        jBrecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrecordActionPerformed(evt);
            }
        });

        jBstock.setBackground(new java.awt.Color(255, 51, 0));
        jBstock.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jBstock.setText("Registration");
        jBstock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBstockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBproducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBsell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBrecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBstock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jBproducts)
                .addGap(33, 33, 33)
                .addComponent(jBsell)
                .addGap(30, 30, 30)
                .addComponent(jBrecord)
                .addGap(28, 28, 28)
                .addComponent(jBstock)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBproductsActionPerformed
        // TODO add your handling code here:
        
        new AddProducts().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBproductsActionPerformed

    private void jBsellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsellActionPerformed
        // TODO add your handling code here:
        new SoldProductInsert().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBsellActionPerformed

    private void jBrecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrecordActionPerformed
        // TODO add your handling code here:
        new Record().setVisible(true);
        dispose();
    }//GEN-LAST:event_jBrecordActionPerformed

    private void jBstockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBstockActionPerformed
        // TODO add your handling code here:
        new Customer().setVisible(true);
    }//GEN-LAST:event_jBstockActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBproducts;
    private javax.swing.JButton jBrecord;
    private javax.swing.JButton jBsell;
    private javax.swing.JButton jBstock;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
